version: '3.8'

services:
  postgres:
    image: postgres-multidb
    container_name: postgres
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: springsandboxdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-sandbox-java:
    image: spring-sandbox-java:dev
    container_name: spring-sandbox-java
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: springsandboxdb
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - /Users/quentin/.m2:/root/.m2
      - /Users/quentin/Programmation/spring-sandbox-java/:/src

networks:
  default:
    name: spring-sandbox-java

volumes:
  postgres-data:
    name: postgres-data
